### ISSUE TITLE
What's the favorite module you've made and why?

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ama#10]

**Comment by vadimdemedes** [comment]
Ooooh that is a tough question. I guess my favorite one has to be [Mongorito](https://github.com/vdemedes/mongorito). It meant many things to me:
1. First major open-source project
2. Introduced me to generators, which leads to the next point
3. Transformed the way I write JavaScript
4. Most popular project so far (although [Trevor](https://github.com/vdemedes/trevor) is catching up fast)
5. Looks like it still does not have competitors with a similar feature set
6. I saw a module once, it said "Inspired by Mongorito", it meant a lot to me

**Comment by sindresorhus** [comment]
> I saw a module once, it said "Inspired by Mongorito", it meant a lot to me

:D
