### ISSUE TITLE
What did you have for breakfast?

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ama#12]

**Comment by vadimdemedes** [comment]
Oatmeal + banana + raisins + nuts:

![photo nov 04 9 24 16 am](https://cloud.githubusercontent.com/assets/697676/11022339/849b3ad6-865c-11e5-864c-ba3f274a8d94.jpg)

Yummy, huh?

**Comment by sindresorhus** [comment]
I hope you had some milk in there too.

And btw, you close the issues when answered ;)

**Comment by vadimdemedes** [comment]
Nope, no milk!

> And btw, you close the issues when answered ;)

Yeah, I know, I just leave them open for a few minutes after I reply :)

**Comment by sindresorhus** [comment]
Wat, that's not human food :p

**Comment by vadimdemedes** [comment]
Haha, yeah, I am on a diet :D Every meal is documented and scheduled using cron jobs.

**Comment by sindresorhus** [comment]
I'm gonna go out and have a cheeseburger right now for you.

**Comment by vadimdemedes** [comment]
What are you doing??? I already watched a friend eating burger at McDonalds yesterday, I am on the edge!
