### ISSUE TITLE
Other than Javascript, what is your favorite language?

### ISSUE THREAD

**Issue by Qix-** [vadimdemedes/ama#19]

**Comment by vadimdemedes** [comment]
I'm not a pervert, really, but I do enjoy bash occasionally. 

I am also a fan of [Crystal](http://crystal-lang.org/), very interesting how it will turn out. It's a Ruby-like language, except it compiles to a binary. Already tried it in [one project](https://github.com/vdemedes/mustached) and was satisfied with the results.
