### ISSUE TITLE
Blogging Platform: I see that you are using metalsmith for your blog but have a side project git:ghost, do you prefer metalsmith over ghost?

### ISSUE THREAD

**Issue by rclanan** [vadimdemedes/ama#20]
Currently I run Jekyll but have been looking at moving over to a node based platform since I am using node more heavily these days. So just curious your thoughts there. 

Nice work on your open source contributions by the way!

**Comment by vadimdemedes** [comment]
I just wanted to experiment with static site generation. If I had a company blog to run, where I'd need something more stable, I'd probably go with ghost or wordpress.

It is totally up to you. I recommend you to pick convenience over any kind of buzz. Always choose the tools you know and are comfortable with.

> Nice work on your open source contributions by the way!

Thank you!
