### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ama#5]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by vadimdemedes** [comment]
**Editor**: Atom as of last week, Sublime before.

**Terminal**: iTerm + custom prompt to show the current git branch.
<img width="129" alt="screen shot 2015-11-08 at 9 33 23 pm" src="https://cloud.githubusercontent.com/assets/697676/11022466/60223dc2-8660-11e5-82a0-85c7f8aaa58d.png">

**Tools**: macbook pro, beats by dre, text editor, terminal and great House music are the only things I need to rock the world.

**Themes and Fonts**: One Dark + Monaco font
<img width="411" alt="screen shot 2015-11-08 at 9 30 39 pm" src="https://cloud.githubusercontent.com/assets/697676/11022457/02ede9e4-8660-11e5-90bf-f9386ae995bf.png">

**Process**: "Go fucking do it" couldn't describe my process better!
