### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ama#7]

**Comment by vadimdemedes** [comment]
Oh, I still remember this priceless moment, like it was yesterday.

It was a week after I started learning JavaScript. jQuery was so popular, that every beginner knew what it was. So, as a true JavaScript developer, I decided to make my own thing. For some reason, I also thought it would be cool to code the whole library without saving it once and checking whether it works at all.

I think, I believed if I could write the code "blind", without checking & running it continuously, I'd be able to conquer the world.

1 hour, 2 hours, 3 hours pass. Around 500-700 lines of code written in a single file. I was so proud of myself. It's only been a week and here I am, writing the JS code like a ninja. I even bragged about this "achievement" to my parents.

Little did I know, there were some troubles with the energy supply in my city and we lost the power at our apartment. The whole building was blacked out. Computer obviously turned off. I started praying that somehow my work got saved, but unfortunately, I am a realist. Miracles don't happen just like that, when you need them to happen. I was sitting in front of the computer quietly, without saying a single word. 1 minute later power came back on, but it was to late to hit Ctrl + S, there was nothing to save.

I remember, that I just lost my shit inside, turned off the computer and went to do something else.
